### ISSUE TITLE
add -pretty option

### ISSUE THREAD

**Issue by client9** [jgautheron/gogetimports#1]
thanks for a interesting project!

Just found this... and tried it out.  It might be nice to have a `-pretty` option to emit a human readable version via https://golang.org/pkg/encoding/json/#MarshalIndent

regards,

n

**Comment by jgautheron** [comment]
My pleasure! you seem to be interested in developer tools, would you like giving me some feedback about another project I've been working on for a while? (Go quality dashboard)

**Comment by client9** [comment]
re:  (Go quality dashboard)

sure, let me know where to find it.

you might also like http://goreportcard.com if you are not familiar.

regards,

n

**Comment by jgautheron** [comment]
@client9 here's the link to the alpha version: http://exago.io/
I am aware of the existence of `goreportcard`, but as you'll see `exago` is pretty different.
